title: Your awesome title
author: kumaresh
email: kumaresh221b@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! I am Kumaresh.

# social links
twitter_username: kumareshramesh # DO NOT include the @ character, or else the build will fail!
github_username: kachumbers # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
